import { PrismaClient, CognitiveArea, ExerciseType } from '@prisma/client';

const prisma = new PrismaClient();

const exercises: Array<{
  slug: string;
  title: string;
  description: string;
  cognitiveArea: CognitiveArea;
  type: ExerciseType;
  minLevel: number;
  maxLevel: number;
}> = [
  // ATENCIÓN
  {
    slug: 'cancellation',
    title: 'Cancelación de símbolos',
    description: 'Pulsa todos los símbolos que coincidan con el objetivo en la cuadrícula.',
    cognitiveArea: 'ATTENTION',
    type: 'CANCELLATION',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'visual-search',
    title: 'Búsqueda visual',
    description: 'Encuentra el elemento objetivo entre los distractores.',
    cognitiveArea: 'ATTENTION',
    type: 'VISUAL_SEARCH',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'go-no-go',
    title: 'Go/No-Go',
    description: 'Pulsa solo cuando aparece el estímulo objetivo. No respondas al distractor.',
    cognitiveArea: 'ATTENTION',
    type: 'GO_NO_GO',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'divided-attention',
    title: 'Atención dividida',
    description: 'Atiende a dos tareas simultáneamente.',
    cognitiveArea: 'ATTENTION',
    type: 'DIVIDED_ATTENTION',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'alternating-attention',
    title: 'Atención alternante',
    description: 'Alterna entre dos reglas de respuesta según la señal visual.',
    cognitiveArea: 'ATTENTION',
    type: 'ALTERNATING_ATTENTION',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'attention-span',
    title: 'Span atencional',
    description: 'Recuerda qué elementos se iluminaron brevemente en la cuadrícula.',
    cognitiveArea: 'ATTENTION',
    type: 'ATTENTION_SPAN',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'reaction-time',
    title: 'Tiempo de reacción',
    description: 'Pulsa lo más rápido posible cuando aparezca el estímulo.',
    cognitiveArea: 'ATTENTION',
    type: 'REACTION_TIME',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'vigilance',
    title: 'Vigilancia',
    description: 'Detecta los estímulos objetivo en una tarea sostenida de larga duración.',
    cognitiveArea: 'ATTENTION',
    type: 'VIGILANCE',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'auditory-attention',
    title: 'Atención auditiva selectiva',
    description: 'Escucha la secuencia y pulsa solo ante la palabra o letra objetivo.',
    cognitiveArea: 'ATTENTION',
    type: 'AUDITORY_ATTENTION',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'visual-tracking',
    title: 'Seguimiento visual',
    description: 'Sigue los objetos objetivo en movimiento entre distractores idénticos.',
    cognitiveArea: 'ATTENTION',
    type: 'VISUAL_TRACKING',
    minLevel: 1,
    maxLevel: 5,
  },
  // MEMORIA
  {
    slug: 'digit-span',
    title: 'Dígitos directos e inversos',
    description: 'Repite la secuencia de dígitos en orden directo o inverso.',
    cognitiveArea: 'MEMORY',
    type: 'DIGIT_SPAN',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'image-pairs',
    title: 'Pares de imágenes',
    description: 'Estudia pares de imágenes y encuentra la pareja de cada una.',
    cognitiveArea: 'MEMORY',
    type: 'IMAGE_PAIRS',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'position-sequences',
    title: 'Secuencias de posiciones',
    description: 'Reproduce la secuencia de casillas iluminadas en la cuadrícula.',
    cognitiveArea: 'MEMORY',
    type: 'POSITION_SEQUENCES',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'face-memory',
    title: 'Memoria de caras',
    description: 'Estudia caras e identifícalas después entre caras nuevas.',
    cognitiveArea: 'MEMORY',
    type: 'FACE_MEMORY',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'word-memory',
    title: 'Memoria de palabras',
    description: 'Recuerda palabras de una lista (reconocimiento o recuerdo libre).',
    cognitiveArea: 'MEMORY',
    type: 'WORD_MEMORY',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'story-memory',
    title: 'Memoria de historias',
    description: 'Responde preguntas sobre una historia tras leerla o escucharla.',
    cognitiveArea: 'MEMORY',
    type: 'STORY_MEMORY',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'prospective-memory',
    title: 'Memoria prospectiva',
    description: 'Durante una tarea principal, recuerda actuar ante un estímulo específico.',
    cognitiveArea: 'MEMORY',
    type: 'PROSPECTIVE_MEMORY',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'semantic-memory',
    title: 'Memoria semántica',
    description: 'Responde preguntas sobre conocimiento general, definiciones y categorías.',
    cognitiveArea: 'MEMORY',
    type: 'SEMANTIC_MEMORY',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'visual-recognition',
    title: 'Reconocimiento visual',
    description: 'Estudia imágenes de objetos e identifícalas después entre objetos nuevos.',
    cognitiveArea: 'MEMORY',
    type: 'VISUAL_RECOGNITION',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'spatial-working-memory',
    title: 'Memoria de trabajo espacial',
    description: 'Recuerda posiciones y actualízalas mentalmente cuando cambian.',
    cognitiveArea: 'MEMORY',
    type: 'SPATIAL_WORKING_MEMORY',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'episodic-memory',
    title: 'Memoria episódica',
    description: 'Recuerda qué objeto estaba en qué lugar y cuándo.',
    cognitiveArea: 'MEMORY',
    type: 'EPISODIC_MEMORY',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'visuospatial-span',
    title: 'Span visoespacial',
    description: 'Toca los bloques en el mismo orden en que se iluminaron.',
    cognitiveArea: 'MEMORY',
    type: 'VISUOSPATIAL_SPAN',
    minLevel: 1,
    maxLevel: 5,
  },
  // FUNCIONES EJECUTIVAS
  {
    slug: 'stroop',
    title: 'Stroop adaptado',
    description: 'Di el color de la tinta de la palabra, no la palabra en sí.',
    cognitiveArea: 'EXECUTIVE_FUNCTIONS',
    type: 'STROOP',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'trail-making',
    title: 'Trail Making A y B',
    description: 'A: conecta números en orden. B: alterna números y letras.',
    cognitiveArea: 'EXECUTIVE_FUNCTIONS',
    type: 'TRAIL_MAKING',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'tower-of-hanoi',
    title: 'Torre de Hanói',
    description: 'Mueve todos los discos al poste destino respetando las reglas.',
    cognitiveArea: 'EXECUTIVE_FUNCTIONS',
    type: 'TOWER_OF_HANOI',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'route-planning',
    title: 'Planificación de rutas',
    description: 'Planifica la ruta más eficiente para visitar todos los puntos del mapa.',
    cognitiveArea: 'EXECUTIVE_FUNCTIONS',
    type: 'ROUTE_PLANNING',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'inhibition',
    title: 'Inhibición (stop-signal)',
    description: 'Responde al estímulo, pero inhibe tu respuesta ante la señal de stop.',
    cognitiveArea: 'EXECUTIVE_FUNCTIONS',
    type: 'INHIBITION',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'cognitive-flexibility',
    title: 'Flexibilidad cognitiva',
    description: 'Clasifica tarjetas según una regla que puede cambiar sin aviso.',
    cognitiveArea: 'EXECUTIVE_FUNCTIONS',
    type: 'COGNITIVE_FLEXIBILITY',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'abstract-reasoning',
    title: 'Razonamiento abstracto',
    description: 'Encuentra el elemento que completa el patrón visual de la matriz.',
    cognitiveArea: 'EXECUTIVE_FUNCTIONS',
    type: 'ABSTRACT_REASONING',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'categorization',
    title: 'Categorización',
    description: 'Clasifica objetos en categorías o encuentra el que no pertenece.',
    cognitiveArea: 'EXECUTIVE_FUNCTIONS',
    type: 'CATEGORIZATION',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'problem-solving',
    title: 'Resolución de problemas',
    description: 'Elige la mejor solución para situaciones de la vida diaria.',
    cognitiveArea: 'EXECUTIVE_FUNCTIONS',
    type: 'PROBLEM_SOLVING',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'design-fluency',
    title: 'Fluidez de diseño',
    description: 'Dibuja el máximo de figuras distintas combinando líneas en la cuadrícula.',
    cognitiveArea: 'EXECUTIVE_FUNCTIONS',
    type: 'DESIGN_FLUENCY',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'n-back',
    title: 'N-back',
    description: 'Indica si el estímulo actual es igual al de N posiciones atrás.',
    cognitiveArea: 'EXECUTIVE_FUNCTIONS',
    type: 'N_BACK',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'dual-task',
    title: 'Doble tarea',
    description: 'Ejecuta dos tareas cognitivas al mismo tiempo.',
    cognitiveArea: 'EXECUTIVE_FUNCTIONS',
    type: 'DUAL_TASK',
    minLevel: 1,
    maxLevel: 5,
  },
  // LENGUAJE
  {
    slug: 'phonological-fluency',
    title: 'Fluidez verbal fonológica',
    description: 'Escribe el máximo de palabras que empiecen por la letra indicada.',
    cognitiveArea: 'LANGUAGE',
    type: 'PHONOLOGICAL_FLUENCY',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'semantic-fluency',
    title: 'Fluidez semántica',
    description: 'Escribe el máximo de elementos de la categoría indicada.',
    cognitiveArea: 'LANGUAGE',
    type: 'SEMANTIC_FLUENCY',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'naming',
    title: 'Denominación',
    description: 'Nombra los objetos mostrados en las imágenes.',
    cognitiveArea: 'LANGUAGE',
    type: 'NAMING',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'comprehension',
    title: 'Comprensión',
    description: 'Ejecuta las órdenes o responde preguntas sobre lo que escuchas o lees.',
    cognitiveArea: 'LANGUAGE',
    type: 'COMPREHENSION',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'repetition',
    title: 'Repetición',
    description: 'Escucha y reproduce palabras, pseudopalabras o frases.',
    cognitiveArea: 'LANGUAGE',
    type: 'REPETITION',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'reading',
    title: 'Lectura',
    description: 'Lee textos y responde preguntas de comprensión.',
    cognitiveArea: 'LANGUAGE',
    type: 'READING',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'writing',
    title: 'Escritura',
    description: 'Escribe palabras al dictado, copia texto o redacta libremente.',
    cognitiveArea: 'LANGUAGE',
    type: 'WRITING',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'prosody',
    title: 'Prosodia',
    description: 'Identifica la emoción o intención comunicativa por la entonación.',
    cognitiveArea: 'LANGUAGE',
    type: 'PROSODY',
    minLevel: 1,
    maxLevel: 5,
  },
  // VISOESPACIAL
  {
    slug: 'mental-rotation',
    title: 'Rotación mental',
    description: 'Decide si dos figuras son iguales o imágenes especulares en distintos ángulos.',
    cognitiveArea: 'VISUOSPATIAL',
    type: 'MENTAL_ROTATION',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'figure-copy',
    title: 'Copia de figuras',
    description: 'Copia la figura geométrica sobre la cuadrícula de puntos.',
    cognitiveArea: 'VISUOSPATIAL',
    type: 'FIGURE_COPY',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'puzzle',
    title: 'Rompecabezas',
    description: 'Ensambla las piezas para reconstruir la imagen.',
    cognitiveArea: 'VISUOSPATIAL',
    type: 'PUZZLE',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'maze',
    title: 'Laberintos',
    description: 'Encuentra la salida navegando por el laberinto.',
    cognitiveArea: 'VISUOSPATIAL',
    type: 'MAZE',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'depth-perception',
    title: 'Percepción de profundidad',
    description: 'Ordena objetos por distancia aparente o identifica el más cercano o lejano.',
    cognitiveArea: 'VISUOSPATIAL',
    type: 'DEPTH_PERCEPTION',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'object-assembly',
    title: 'Ensamblaje de objetos',
    description: 'Identifica el objeto a partir de sus partes desordenadas.',
    cognitiveArea: 'VISUOSPATIAL',
    type: 'OBJECT_ASSEMBLY',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'shape-discrimination',
    title: 'Discriminación de formas',
    description: 'Identifica la figura idéntica al modelo entre los distractores.',
    cognitiveArea: 'VISUOSPATIAL',
    type: 'SHAPE_DISCRIMINATION',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'line-orientation',
    title: 'Orientación de líneas',
    description: 'Haz coincidir la orientación de las líneas con el abanico de referencia.',
    cognitiveArea: 'VISUOSPATIAL',
    type: 'LINE_ORIENTATION',
    minLevel: 1,
    maxLevel: 5,
  },
  // ORIENTACIÓN
  {
    slug: 'temporal-orientation',
    title: 'Orientación temporal',
    description: 'Responde preguntas sobre el día, fecha, mes, año, estación y hora.',
    cognitiveArea: 'ORIENTATION',
    type: 'TEMPORAL_ORIENTATION',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'spatial-orientation',
    title: 'Orientación espacial',
    description: 'Responde preguntas sobre tu ubicación actual e identifica lugares en el mapa.',
    cognitiveArea: 'ORIENTATION',
    type: 'SPATIAL_ORIENTATION',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'personal-orientation',
    title: 'Orientación personal',
    description: 'Responde preguntas sobre tu nombre, edad, profesión y datos biográficos.',
    cognitiveArea: 'ORIENTATION',
    type: 'PERSONAL_ORIENTATION',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'situational-orientation',
    title: 'Orientación situacional',
    description: 'Responde preguntas sobre el contexto y la situación actual.',
    cognitiveArea: 'ORIENTATION',
    type: 'SITUATIONAL_ORIENTATION',
    minLevel: 1,
    maxLevel: 5,
  },
  // COGNICIÓN SOCIAL
  {
    slug: 'emotion-recognition',
    title: 'Reconocimiento de emociones',
    description: 'Identifica la emoción expresada en la cara entre las opciones dadas.',
    cognitiveArea: 'SOCIAL_COGNITION',
    type: 'EMOTION_RECOGNITION',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'theory-of-mind',
    title: 'Teoría de la mente',
    description: 'Infiere qué piensa o siente el personaje de la historia.',
    cognitiveArea: 'SOCIAL_COGNITION',
    type: 'THEORY_OF_MIND',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'empathy',
    title: 'Empatía',
    description: 'Elige la respuesta más empática ante las situaciones sociales.',
    cognitiveArea: 'SOCIAL_COGNITION',
    type: 'EMPATHY',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'perspective-taking',
    title: 'Toma de perspectiva',
    description: 'Adopta el punto de vista visual o cognitivo de otra persona.',
    cognitiveArea: 'SOCIAL_COGNITION',
    type: 'PERSPECTIVE_TAKING',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'moral-cognition',
    title: 'Cognición moral',
    description: 'Evalúa la adecuación de una acción ante dilemas morales.',
    cognitiveArea: 'SOCIAL_COGNITION',
    type: 'MORAL_COGNITION',
    minLevel: 1,
    maxLevel: 5,
  },
  {
    slug: 'nonverbal-communication',
    title: 'Comunicación no verbal',
    description: 'Identifica el significado de gestos y posturas en las imágenes.',
    cognitiveArea: 'SOCIAL_COGNITION',
    type: 'NONVERBAL_COMMUNICATION',
    minLevel: 1,
    maxLevel: 5,
  },
];

async function main() {
  console.log('Seeding exercises...');

  for (const ex of exercises) {
    await prisma.exercise.upsert({
      where: { slug: ex.slug },
      update: {
        title: ex.title,
        description: ex.description,
      },
      create: ex,
    });
  }

  console.log(`Seeded ${exercises.length} exercises.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
